name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: YeahIKnowSometimesThingsMayNotAlwaysMakeSenseToYouRightNowButHeyWhatDaddyAlwaysTellYou
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/infsecuritylab1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: goodstory87

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: goodstory87
          POSTGRES_DB: infsecuritylab1
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d infsecuritylab1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        working-directory: InfSecurityLab1
        run: mvn -B clean verify

      - name: Run SpotBugs
        working-directory: InfSecurityLab1
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.7.3.0:spotbugs

      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: InfSecurityLab1/target/spotbugsXml.xml

      - name: Run Snyk test (SCA)
        working-directory: InfSecurityLab1
        run: |
          npm install -g snyk snyk-to-html
          snyk auth $SNYK_TOKEN
          snyk test --all-projects --json > snyk-report.json || true
          snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: InfSecurityLab1/snyk-report.html

